version: '3.8'

services:
  auth:
    build:
      context: ../auth
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - network

  storage:
    build:
      context: ../storage
      dockerfile: ./build/Dockerfile
    ports:
      - "8090:8090"
    networks:
      - network

  postgres:
    image: postgres:15.3
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - ../db/data:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    env_file:
      - ../configs/.env
    networks:
      - network

networks:
  network:
    driver: bridge
